name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Test
        run: go test ./...
  lint:
    strategy:
      matrix:
        go-version: [1.19.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: reviewdog/action-golangci-lint@v2
  staticcheck:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
